_target_: src.models.simple_lstm_fixed_len_model.SimpleLSTMFixedLenLitModel

vocab_size: 6900
embedding_dim: 128
hidden_dim: 128,
num_classes: 8
dropout_rate: 0.2
lr: 0.001
weight_decay: 0.0005
use_glove_embeddings: False
glove_file_path: /home/gsoykan20/Desktop/self_development/emotion-recognition-drawings/data/glove.6B.50d.txt
use_elmo_embeddings: False